-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('cshead_pb')


local localTable = {}
CSHEAD = protobuf.Descriptor()
localTable.CSHEAD_VER_FIELD = protobuf.FieldDescriptor()
localTable.CSHEAD_SEQ_FIELD = protobuf.FieldDescriptor()
localTable.CSHEAD_FLG_FIELD = protobuf.FieldDescriptor()

localTable.CSHEAD_VER_FIELD.name = "ver"
localTable.CSHEAD_VER_FIELD.full_name = ".CSHead.ver"
localTable.CSHEAD_VER_FIELD.number = 1
localTable.CSHEAD_VER_FIELD.index = 0
localTable.CSHEAD_VER_FIELD.label = 1
localTable.CSHEAD_VER_FIELD.has_default_value = false
localTable.CSHEAD_VER_FIELD.type = 5
localTable.CSHEAD_VER_FIELD.cpp_type = 1

localTable.CSHEAD_SEQ_FIELD.name = "seq"
localTable.CSHEAD_SEQ_FIELD.full_name = ".CSHead.seq"
localTable.CSHEAD_SEQ_FIELD.number = 2
localTable.CSHEAD_SEQ_FIELD.index = 1
localTable.CSHEAD_SEQ_FIELD.label = 1
localTable.CSHEAD_SEQ_FIELD.has_default_value = false
localTable.CSHEAD_SEQ_FIELD.type = 5
localTable.CSHEAD_SEQ_FIELD.cpp_type = 1

localTable.CSHEAD_FLG_FIELD.name = "flg"
localTable.CSHEAD_FLG_FIELD.full_name = ".CSHead.flg"
localTable.CSHEAD_FLG_FIELD.number = 3
localTable.CSHEAD_FLG_FIELD.index = 2
localTable.CSHEAD_FLG_FIELD.label = 1
localTable.CSHEAD_FLG_FIELD.has_default_value = false
localTable.CSHEAD_FLG_FIELD.type = 5
localTable.CSHEAD_FLG_FIELD.cpp_type = 1

CSHEAD.name = "CSHead"
CSHEAD.full_name = ".CSHead"
CSHEAD.nested_types = {}
CSHEAD.enum_types = {}
CSHEAD.fields = {localTable.CSHEAD_VER_FIELD, localTable.CSHEAD_SEQ_FIELD, localTable.CSHEAD_FLG_FIELD}
CSHEAD.is_extendable = false
CSHEAD.extensions = {}

CSHead = protobuf.Message(CSHEAD)

