-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('msghead_pb')


local localTable = {}
MSGHEAD = protobuf.Descriptor()
localTable.MSGHEAD_ID_FIELD = protobuf.FieldDescriptor()
localTable.MSGHEAD_TYPE_FIELD = protobuf.FieldDescriptor()
localTable.MSGHEAD_SEQ_FIELD = protobuf.FieldDescriptor()
localTable.MSGHEAD_SRCET_FIELD = protobuf.FieldDescriptor()
localTable.MSGHEAD_DSTET_FIELD = protobuf.FieldDescriptor()
localTable.MSGHEAD_SRCID_FIELD = protobuf.FieldDescriptor()
localTable.MSGHEAD_DSTID_FIELD = protobuf.FieldDescriptor()
localTable.MSGHEAD_TS_FIELD = protobuf.FieldDescriptor()

localTable.MSGHEAD_ID_FIELD.name = "id"
localTable.MSGHEAD_ID_FIELD.full_name = ".MsgHead.id"
localTable.MSGHEAD_ID_FIELD.number = 1
localTable.MSGHEAD_ID_FIELD.index = 0
localTable.MSGHEAD_ID_FIELD.label = 1
localTable.MSGHEAD_ID_FIELD.has_default_value = false
localTable.MSGHEAD_ID_FIELD.type = 5
localTable.MSGHEAD_ID_FIELD.cpp_type = 1

localTable.MSGHEAD_TYPE_FIELD.name = "type"
localTable.MSGHEAD_TYPE_FIELD.full_name = ".MsgHead.type"
localTable.MSGHEAD_TYPE_FIELD.number = 2
localTable.MSGHEAD_TYPE_FIELD.index = 1
localTable.MSGHEAD_TYPE_FIELD.label = 1
localTable.MSGHEAD_TYPE_FIELD.has_default_value = true
localTable.MSGHEAD_TYPE_FIELD.default_value = 1
localTable.MSGHEAD_TYPE_FIELD.type = 5
localTable.MSGHEAD_TYPE_FIELD.cpp_type = 1

localTable.MSGHEAD_SEQ_FIELD.name = "seq"
localTable.MSGHEAD_SEQ_FIELD.full_name = ".MsgHead.seq"
localTable.MSGHEAD_SEQ_FIELD.number = 3
localTable.MSGHEAD_SEQ_FIELD.index = 2
localTable.MSGHEAD_SEQ_FIELD.label = 1
localTable.MSGHEAD_SEQ_FIELD.has_default_value = true
localTable.MSGHEAD_SEQ_FIELD.default_value = 1
localTable.MSGHEAD_SEQ_FIELD.type = 5
localTable.MSGHEAD_SEQ_FIELD.cpp_type = 1

localTable.MSGHEAD_SRCET_FIELD.name = "srcEt"
localTable.MSGHEAD_SRCET_FIELD.full_name = ".MsgHead.srcEt"
localTable.MSGHEAD_SRCET_FIELD.number = 4
localTable.MSGHEAD_SRCET_FIELD.index = 3
localTable.MSGHEAD_SRCET_FIELD.label = 1
localTable.MSGHEAD_SRCET_FIELD.has_default_value = false
localTable.MSGHEAD_SRCET_FIELD.type = 5
localTable.MSGHEAD_SRCET_FIELD.cpp_type = 1

localTable.MSGHEAD_DSTET_FIELD.name = "dstEt"
localTable.MSGHEAD_DSTET_FIELD.full_name = ".MsgHead.dstEt"
localTable.MSGHEAD_DSTET_FIELD.number = 5
localTable.MSGHEAD_DSTET_FIELD.index = 4
localTable.MSGHEAD_DSTET_FIELD.label = 1
localTable.MSGHEAD_DSTET_FIELD.has_default_value = false
localTable.MSGHEAD_DSTET_FIELD.type = 5
localTable.MSGHEAD_DSTET_FIELD.cpp_type = 1

localTable.MSGHEAD_SRCID_FIELD.name = "srcId"
localTable.MSGHEAD_SRCID_FIELD.full_name = ".MsgHead.srcId"
localTable.MSGHEAD_SRCID_FIELD.number = 6
localTable.MSGHEAD_SRCID_FIELD.index = 5
localTable.MSGHEAD_SRCID_FIELD.label = 1
localTable.MSGHEAD_SRCID_FIELD.has_default_value = false
localTable.MSGHEAD_SRCID_FIELD.type = 13
localTable.MSGHEAD_SRCID_FIELD.cpp_type = 3

localTable.MSGHEAD_DSTID_FIELD.name = "dstId"
localTable.MSGHEAD_DSTID_FIELD.full_name = ".MsgHead.dstId"
localTable.MSGHEAD_DSTID_FIELD.number = 7
localTable.MSGHEAD_DSTID_FIELD.index = 6
localTable.MSGHEAD_DSTID_FIELD.label = 1
localTable.MSGHEAD_DSTID_FIELD.has_default_value = false
localTable.MSGHEAD_DSTID_FIELD.type = 13
localTable.MSGHEAD_DSTID_FIELD.cpp_type = 3

localTable.MSGHEAD_TS_FIELD.name = "ts"
localTable.MSGHEAD_TS_FIELD.full_name = ".MsgHead.ts"
localTable.MSGHEAD_TS_FIELD.number = 8
localTable.MSGHEAD_TS_FIELD.index = 7
localTable.MSGHEAD_TS_FIELD.label = 1
localTable.MSGHEAD_TS_FIELD.has_default_value = false
localTable.MSGHEAD_TS_FIELD.type = 1
localTable.MSGHEAD_TS_FIELD.cpp_type = 5

MSGHEAD.name = "MsgHead"
MSGHEAD.full_name = ".MsgHead"
MSGHEAD.nested_types = {}
MSGHEAD.enum_types = {}
MSGHEAD.fields = {localTable.MSGHEAD_ID_FIELD, localTable.MSGHEAD_TYPE_FIELD, localTable.MSGHEAD_SEQ_FIELD, localTable.MSGHEAD_SRCET_FIELD, localTable.MSGHEAD_DSTET_FIELD, localTable.MSGHEAD_SRCID_FIELD, localTable.MSGHEAD_DSTID_FIELD, localTable.MSGHEAD_TS_FIELD}
MSGHEAD.is_extendable = false
MSGHEAD.extensions = {}

MsgHead = protobuf.Message(MSGHEAD)

