-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Student_pb')


local localTable = {}
INFO = protobuf.Descriptor()
localTable.INFO_NAME_FIELD = protobuf.FieldDescriptor()
STUDENT = protobuf.Descriptor()
localTable.STUDENT_COUNT_FIELD = protobuf.FieldDescriptor()
localTable.STUDENT_INFOS_FIELD = protobuf.FieldDescriptor()

localTable.INFO_NAME_FIELD.name = "name"
localTable.INFO_NAME_FIELD.full_name = ".Info.name"
localTable.INFO_NAME_FIELD.number = 1
localTable.INFO_NAME_FIELD.index = 0
localTable.INFO_NAME_FIELD.label = 2
localTable.INFO_NAME_FIELD.has_default_value = false
localTable.INFO_NAME_FIELD.type = 9
localTable.INFO_NAME_FIELD.cpp_type = 9

INFO.name = "Info"
INFO.full_name = ".Info"
INFO.nested_types = {}
INFO.enum_types = {}
INFO.fields = {localTable.INFO_NAME_FIELD}
INFO.is_extendable = false
INFO.extensions = {}
localTable.STUDENT_COUNT_FIELD.name = "count"
localTable.STUDENT_COUNT_FIELD.full_name = ".Student.count"
localTable.STUDENT_COUNT_FIELD.number = 1
localTable.STUDENT_COUNT_FIELD.index = 0
localTable.STUDENT_COUNT_FIELD.label = 2
localTable.STUDENT_COUNT_FIELD.has_default_value = false
localTable.STUDENT_COUNT_FIELD.type = 5
localTable.STUDENT_COUNT_FIELD.cpp_type = 1

localTable.STUDENT_INFOS_FIELD.name = "infos"
localTable.STUDENT_INFOS_FIELD.full_name = ".Student.infos"
localTable.STUDENT_INFOS_FIELD.number = 2
localTable.STUDENT_INFOS_FIELD.index = 1
localTable.STUDENT_INFOS_FIELD.label = 3
localTable.STUDENT_INFOS_FIELD.has_default_value = false
localTable.STUDENT_INFOS_FIELD.default_value = {}
localTable.STUDENT_INFOS_FIELD.message_type = INFO
localTable.STUDENT_INFOS_FIELD.type = 11
localTable.STUDENT_INFOS_FIELD.cpp_type = 10

STUDENT.name = "Student"
STUDENT.full_name = ".Student"
STUDENT.nested_types = {}
STUDENT.enum_types = {}
STUDENT.fields = {localTable.STUDENT_COUNT_FIELD, localTable.STUDENT_INFOS_FIELD}
STUDENT.is_extendable = false
STUDENT.extensions = {}

Info = protobuf.Message(INFO)
Student = protobuf.Message(STUDENT)

